export const SUBMIT_REGISTRATION_DATA = 'nextmain/register/SUBMIT_REGISTRATION_DATA';
export const SUBMIT_REGISTRATION_DATA_SUCCESS = 'nextmain/register/SUBMIT_REGISTRATION_DATA_SUCCESS';
export const SUBMIT_REGISTRATION_DATA_ERROR = 'nextmain/register/SUBMIT_REGISTRATION_DATA_ERROR';

export const STORE_STEP1 = 'nextmain/register/STORE_STEP1';